### ISSUE TITLE
pi2jamma JAMMA controls

### ISSUE THREAD

**Issue by xovox** [xovox/RetroCRT#19]
* RetroCRT.yml should always compile, configure & install pikeyd165
* /boot/retrocrt/pi2jamma
```
pi2jamma_controls=enable
```
* autostart.sh 
  * source pi2jamma config file & start pikeyd if enabled

**Comment by xovox** [comment]
```
    - name: "pikeyd: compile"                                                                                                          
      make:                                                                                                                            
        chdir: "/home/pi/RetroCRT/pikeyd"   
```

**Comment by xovox** [comment]
https://github.com/xovox/regamebox_pikeyd165

**Comment by InSL** [comment]
I'm looking forward to this feature! I would like to run you nice RetroCRT image in my arcade cabinet😊 Keep up the good work!

**Comment by golden-braid** [comment]
Any news on when Jamma controls will be supported? Keen to setup the RetroCRT image in my cabinet.. best wishes!

**Comment by xovox** [comment]
hey guys, sorry that development on this project has stalled!  since I've started this project, I've acquired a few dedicated cabinets & have been trying to get the #2 high score for Rolling Thunder on my dedicated cabinet. haha

I'm going to start focusing on this again this fall, jamma controls are #1 on my list of things to work on

**Comment by golden-braid** [comment]
This is awesome news – cannot wait to setup your build in my cabinet!

Kind Regards,
Sam

Sam Jersche
sam@sjediting.com<mailto:sam@sjediting.com>
Copyediting & Proofreading
M (+44) 7984 623 785
www.sjediting.com<http://www.sjediting.com>

**Comment by golden-braid** [comment]
This is awesome news – cannot wait to setup your build in my cabinet!

**Comment by xovox** [comment]
this is going to be split off into another project to simplify everything for me

https://github.com/xovox/RetroJAMMA
