### ISSUE TITLE
Fix splash screens

### ISSUE THREAD

**Issue by xovox** [xovox/RetroCRT#29]
This has been broken for a while now.  Thankfully, I found a neat little tool & figured out how to use it!  I'm so super clever!  Look at me!  Will any ever actually read this?!

this depends on the xml-twig-tools package

The following is *really* slow at 2 seconds on my straight 3B, but i can just cache the result so it'll be quick the next time.
 
```
xml_grep \
  --text_only \
  "/gameList/game[@id='mspacman']/image" \
  $HOME/RetroPie/roms/fba/gamelist.xml
```

**Comment by xovox** [comment]
```
pi@retropie:~/RetroPie/roms/fba $ time xml_grep --text_only "/gameList/game[@id='mspacman']/image" gamelist.xml 
/home/pi/RetroPie/media/arcade/image/mspacman-image.png

real    0m2.103s
user    0m2.023s
sys     0m0.071s
```

**Comment by strayel** [comment]
Does this depend on all snaps of ROMs being scraped to be displayed? If so a single system splash screen would suffice for the amount of time it's displayed. This RetroCRT build is pretty damn awesome the way the resolutions work.
