### ISSUE TITLE
Garbled Colors on Sony Trinitron

### ISSUE THREAD

**Issue by ghost** [xovox/RetroCRT#39]
Hello. I've tried following the instructions exactly how they were laid out. I'm using the RetroTink Ultimate and component cables on a Raspberry pi 3B+. I've updated everything and still end up with very bad colors. I also made sure that dpi_output_format=0 was correct in the config file before starting the process. Any help?

**Comment by xovox** [comment]
hi!  i'm sorry that it's taken a bit to get back to you, i've been on a computer sabbatical for the last 4 months.

is this a retrotink ultimate sold by mike chi or is it one of the newer ones?

**Comment by xovox** [comment]
try this:

go into the retropie menu in ES, select RetroCRT.  Once in there, select the correct hardware for your system.  the colors are probably because it defaults to VGA666

**Comment by ghost** [comment]
Hey, thanks for the reply. I think it was sold by Mike Chi. I bought it back in 2017/2018 (I don't fully remember the date). 
I'll try that once I get a chance. I need to create a new image (no idea where any are for the retrotink ultimate anymore) before I can test that out. Currently, I'm retrying my hand at creating a retro pc that uses groovymame, outputs vga, using a vga to component transcoder, then outputting component to my Sony Trinitron. Tried it years back, failed and I plan to try again.

**Comment by ghost** [comment]
Disregard part of what I said early, I forgot you have that image.

**Comment by ghost** [comment]
> try this:
> 
> go into the retropie menu in ES, select RetroCRT. Once in there, select the correct hardware for your system. the colors are probably because it defaults to VGA666

Morning. Thanks again for your input. Before when I used to set this up, your instructions wouldn't have worked but I think enough updates were made that it worked 100% with the instructions provided. 

Side question...Any plans to get retrotink ultimate to work with RPi4? Honestly I mainly wanted RPi4 to output component for the N64/Saturn/Arcade emulators. RPi3B+, as far as I know, is terrible when it comes to N64/Saturn. So for now, I'll be using this strictly for arcade games (I also have a MiSTer for the 16bit consoles).

**Comment by ghost** [comment]
I spoke too soon. It worked, then randomly as I was removing and adding cores the color went back to being garbled. 
Here is my set up and my current config.txt settings:
TV - Sony KV-27FS13
Raspberry Pi - 3B+
Retrotink Ultimate
Retrotink Ultimate Component output to TV Component input
Image - RetroCRT-20200108-rpi3
I also tried the setting change within your instructions (You'll need to update /boot/config.txt and set the following to 519 for RetroTink & 0 for all other platforms. "dpi_output_format=0")

Config.txt:
```
# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable the lirc-rpi module
#dtoverlay=lirc-rpi

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on
gpu_mem_256=128
gpu_mem_512=256
gpu_mem_1024=256
overscan_scale=1
dtoverlay=dpi24
enable_dpi_lcd=1
display_default_lcd=1
dpi_group=2
dpi_mode=87
disable_splash=1
hdmi_timings=320 1 16 30 34 240 1 2 3 22 0 0 0 60 0 6400000 1

# 519 for RetroTink Ultimate
# 0 for everything else
dpi_output_format=519
force_turbo=0
disable_audio_dither=1
audio_pwm_mode=0
```

**Comment by xovox** [comment]
sadly, i don't have any real plans to support RPi4 at this time.  i bought one when they first came out to port everything oer to it. 

I haven't experimented yet, but my understanding is that you can't do dynamic resolution changes... so i wouldn't be able to switch between 320x240 for ES and then 1920xNNN for the games... if ES had the ability to stretch & not scale for menuing, it'd work out ok since the user wouldn't notice anything


> Side question...Any plans to get retrotink ultimate to work with RPi4? Honestly I mainly wanted RPi4 to output component for the N64/Saturn/Arcade emulators. RPi3B+, as far as I know, is terrible when it comes to N64/Saturn. So for now, I'll be using this strictly for arcade games (I also have a MiSTer for the 16bit consoles).

**Comment by xovox** [comment]
oof, that's something i don't have an answer for.  maybe a loose connection between the pi & rt?  


> I spoke too soon. It worked, then randomly as I was removing and adding cores the color went back to being garbled.
> Here is my set up and my current config.txt settings:
> TV - Sony KV-27FS13
> Raspberry Pi - 3B+
> Retrotink Ultimate
> Retrotink Ultimate Component output to TV Component input
> Image - RetroCRT-20200108-rpi3
> I also tried the setting change within your instructions (You'll need to update /boot/config.txt and set the following to 519 for RetroTink & 0 for all other platforms. "dpi_output_format=0")

**Comment by xovox** [comment]
you should join us in the official FB group https://www.facebook.com/groups/RetroPieCRT

i'm going to close this issue
