### ISSUE TITLE
Calculate hdmi_timings for Raspberry Pi 4

### ISSUE THREAD

**Issue by phantom-voltage** [xovox/RetroCRT#45]
According to a [RetroRGB article](https://www.retrorgb.com/retrotink-ultimate-working-on-raspberry-pi-4.html) the DPI has changed from previous models (source?). In my own tests, I can confirm that video output for Raspberry Pi 4 Model B using the `hdmi_timings` provided in RetroCRT (RetroCRT3 "Dark Odyssey" Beta (20210617)) `boot/config.txt files`, that the video output no longer functions properly (black screen). 

The original work to get the new `hdmi_timings` for Lakka appears to be from this [forum post](https://forums.libretro.com/t/lakka-pi-4-retrotink-ultimate-rgb-crt/25508). These timings for Lakka are not suitable for EmulationStation in my experience. The resolution is scaled to a large horizontal value for what I'm assuming is pixel perfect scaling, with a matching pixel frequency. If relied on for solely rgui, the interface can be scaled accordingly. EmulationStation in my experience can not scale accordingly.

 I found [another user also attempting to solve these problems](https://www.raspberrypi.org/forums/viewtopic.php?t=24679&start=225) with the Raspberry Pi 4, although using the vga666 hat.  

HDMI timings for RetroTink and other hats need to be configured to support Raspberry Pi 4. 

I am not sure if anyone is working on this. I'll work on this when possible, although not my area of expertise.

**Comment by xovox** [comment]
hi!  I haven't been paying close attention to this project lately, but I just put a pi4 into my JAMMA cabinet.  there are 3rd party drivers I'm going to use for everything to get it working on the pi4.  I absolutely want help with everything on here.  

are you in the FB group https://www.facebook.com/groups/2363533017255110 ?

**Comment by xovox** [comment]
https://github.com/xovox/rpi-dpidac

**Comment by xovox** [comment]
http://mydedibox.fr/rpi4-custom-modes-on-a-crt-tv-the-holy-grail
