### ISSUE TITLE
apt metadata not being updated by setup script

### ISSUE THREAD

**Issue by Dochartaigh** [xovox/RetroCRT#46]
Following directions posted here: https://github.com/xovox/RetroCRT/blob/master/MANUAL.md

To "Update RetroPie":

Run RetroPie Setup from the RetroPie screen in EmulationStation
Option U "Update"
"Yes" to update installed packages
Update underlying OS packages

I was NOT able to do the above. The developer said to report it here and attach these screenshots of the error (this was a CRT Retropie build so excuse the screenshots). I can't really add anything else as I don't really know what this means TBH...

![271961723_751944785772121_5121268300169067130_n](https://user-images.githubusercontent.com/23370177/150990562-b74ae7f0-1c67-47dc-9556-a865f94ca190.png)
![271635860_1152737902130243_3168849865248170145_n](https://user-images.githubusercontent.com/23370177/150990567-45561312-41c4-4223-9e8d-48b0256949aa.png)
![271902447_625842125358210_6432303314763722873_n](https://user-images.githubusercontent.com/23370177/150990573-a4f6cf57-2010-4e4e-975a-b4c609236f27.png)
)

**Comment by xovox** [comment]
fixed
